# models/sources.yml

version: 2

sources:
  - name: raw
    description: "Source data from the raw e-commerce dataset."
    database: ecommerce_data
    schema: raw_ecommerce
    tables:
      - name: raw_ecommerce_data
        description: "Raw e-commerce data loaded from the CSV file."
